# Generated by Django 4.1.5 on 2023-06-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=50)),
                ('contact', models.IntegerField(max_length=10)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
